### ISSUE TITLE
Cannot Copy/Paste

### ISSUE THREAD

**Issue by mlucool** [gaearon/redux-devtools-log-monitor#18]
Hi,

I cannot highlight to copy/paste the data in the devtools default UI. It won't highlight the text on using chrome 47. This is intentional due to: : chibicode/react-json-tree#10

Another very useful feature would be to serialize either the action or the state to JSON and then to the clipboard. A simple export button would be sufficient and an easy, while getting diffs or a whole state would be even better.

Reporting in the right project from: https://github.com/gaearon/redux-devtools/issues/200

**Comment by gaearon** [comment]
I agree those would be useful, but I don’t currently have time to implement them. If you feel like doing it without making UI too noisy, please go for it! But I’ll close as this is not actionable for me in the observable future.
