### ISSUE TITLE
Action value overflow issue

### ISSUE THREAD

**Issue by VinSpee** [gaearon/redux-devtools-log-monitor#22]
Hi! I noticed a small bug when working on an API that returns a huge hash URL. The monitor overflows horizontally with scroll (expected behavior I presume, but maybe wrapping would be better? It would in this instance but maybe not always), but the background color does not grow with it.

I'd like to cook up a PR for this, and if all goes well, for #1 later. Let me know what you think about overflow vs wrapping!

![overflow](https://cloud.githubusercontent.com/assets/582828/12036511/a72465f2-ae14-11e5-9e27-20f32d533c1e.gif)

**Comment by gaearon** [comment]
PR would be most welcome.

**Comment by gaearon** [comment]
Ping @VinSpee. Any interest in creating a PR? Thanks.

**Comment by VinSpee** [comment]
Hey sorry - upon further investigation it appears like the issue is in [react-json-tree](https://github.com/chibicode/react-json-tree). 

I moved the issue there chibicode/react-json-tree#42 

I'll let you decide if you want to keep this open until it's resolved there and bumped here or close

**Comment by gaearon** [comment]
:+1: Let’s keep it there then, please reopen if it’s not fixable there.
