### ISSUE TITLE
Getting "Error selecting state." when using custom selector

### ISSUE THREAD

**Issue by danny-andrews** [gaearon/redux-devtools-log-monitor#27]
When I try to use a custom state selector, I get "Error selecting state." printed under `@@INIT` action. It appears state is null during this action, because I can't even select a top level property, e.g. `state => state.propA`. Is this by design?

**Comment by gaearon** [comment]
Hmm, good catch. Maybe we shouldn't call `selectState` when root state is undefined? I'd be happy to accept a PR for this.

**Comment by danny-andrews** [comment]
Great, on it!

**Comment by gaearon** [comment]
Fixed in 1.0.4, thank you for reporting and working on this.
