### ISSUE TITLE
Style gets messed up after a few actions

### ISSUE THREAD

**Issue by jlongster** [gaearon/redux-devtools-log-monitor#3]
I have no idea why this is happening. I'm using redux in the Firefox debugger and I just integrated the latest (3.0.0) redux-devtools, and it looks like this:

<img width="573" alt="0cd98007-ceb8-425a-a306-a6358aaaac07" src="https://cloud.githubusercontent.com/assets/17031/10674612/f8a7bea4-78c9-11e5-93d4-7edf6dbe36a1.png">

I fixed that `undefined` that we were seeing earlier. I'm rendering it like this:

```js
    const win = window.open(
      'data:text/html,<!DOCTYPE html><html style="height:100%"><body style="height:100%;margin:0"></body></html>',
      "redux-devtools",
      "menubar=no,location=no,resizable=yes,scrollbars=no,status=no"
    );

    // Install the devtools. Timeout just to be sure (just for testing)
    setTimeout(() => {
      React.render(
        React.createElement(
          Provider, { store: store },
          React.createElement(reduxDevTools)
        ),
        win.document.body
      );
    }, 500);
```

**Comment by jlongster** [comment]
This happens if I render it in the same window, too, but the above just makes sure that there are no other styles messing w/it.

**Comment by gaearon** [comment]
Maybe we could try replacing some Flex styles with box model. Flex styles often have weird layout issues.

**Comment by jlongster** [comment]
I'm surprised others haven't seen this though, which makes me suspect that something is weird in my env. I also can't even seem to fix it by playing around with the styles in devtools..

Trying to get @dzannotti my state so he can locally load it up and check it out.

**Comment by dzannotti** [comment]
@gaearon i don't think you are far from what it looks like to me :)
Flex is only used for buttons, but i suspect that a problem in firefox forces subsequent child with no display value to stick to previous display (flex row?), I can't see any other way to obtain this behaviour

**Comment by jlongster** [comment]
I figured it out.

It was my setup.

It was the demon from hell.

[XUL](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL).

*Even though* I was opening a new window, setting the doctype to `html` and it looked like it was a normal HTML page, somehow it was still inheriting all the bad stuff from XUL. One of them being that elements have `display: -moz-box` by default instead of `display: block`.

You all don't need to change anything, I can just try to fix `display` defaults with crazy CSS!

**Comment by gaearon** [comment]
Good old XUL. Yes I remember that from my Firefox Addons days.
