### ISSUE TITLE
Sort state keys alphabetically

### ISSUE THREAD

**Issue by Mistereo** [gaearon/redux-devtools-log-monitor#30]
Can we add ability to show state keys in alphabetical order?

**Comment by rockingskier** [comment]
Sounds like a feature for [`react-json-tree`](https://github.com/chibicode/react-json-tree) rather than `redux-devtools-log-monitor`

**Comment by gaearon** [comment]
Yes, please lobby `react-json-tree` to support this if you’re interested. That said I think there are advantages to representing the objects the same way Chrome DevTools represent them: by definition order.

**Comment by dahjelle** [comment]
Looks like [`react-json-tree` has added the option to sort by keys](https://github.com/alexkuz/react-json-tree/issues/37). My naïve question, then: is that feature already exposed some way by log-monitor (and especially in the DevTools Chrome extension)?

**Comment by denis-sokolov** [comment]
@gaearon, @Mistereo, could we please reopen this? Navigating a big state tree is more inconvenient than it has to be. Imagine a phonebook sorted by the contract signing date instead of by name.

In my unsubstantiated opinion, a vast majority of Redux users use the state tree as an unordered map. All those users would prefer a sorted tree that optimizes the search for a key.

**Comment by gasi** [comment]
Agreed, could we please reopen this? It’s very difficult scanning large state trees if the keys are not sorted alphabetically, literally `O(n)` instead of `O(log n)` (binary search) 😉

**Comment by brandondurham** [comment]
I, too, have a huge state tree to navigate, and it‘s painful.

**Comment by DmacVeem** [comment]
This would be extremely helpful. Trying to find the key in an enormous state can be difficult.

**Comment by gasi** [comment]
@brandondurham @DmacVeem In case it helps, I worked around the issue by initializing my Redux store using keys in alphabetical order, e.g.

```javascript
{
  isFilterActive: false,
  media: {
    byId: {
      // …
    },
  },
  messages: [],
  // …
}
```

JavaScript for some reason enumerates keys in insertion order so initializing like this will present the tree with alphabetically sorted keys. Hope this helps 😄

**Comment by hugotox** [comment]
+1

**Comment by hugotox** [comment]
does anybody know a workaround or fork to get this sorted?

**Comment by arunmmanoharan** [comment]
`export default combineReducers(
	Object.fromEntries(
		Object.entries({
			//Your reducers here and this should be fixed
		}).sort()
	)
);`

**Comment by JimbobTheSailor** [comment]
@a2441918 Can you please elaborate on your above solution? Where does this code go? Does it work when modules are lazy loaded?

**Comment by arunmmanoharan** [comment]
I havent tried lazy load, but it should as the sorting is done only on the rootReducer level. One catch is that you can only sort the main parent keys, but not the child keys.

**Comment by JimbobTheSailor** [comment]
@a2441918 . Thanks for quick response. Can you elaborate on where your code is inserted into the project?

**Comment by arunmmanoharan** [comment]
> @a2441918 . Thanks for quick response. Can you elaborate on where your code is inserted into the project?

In the main rootReducer.

	export default history =>
		combineReducers(
			Object.fromEntries(
				Object.entries({
					router: connectRouter(history),
					...otherReducers
				}).sort()
			)
		);

**Comment by RobertHeim** [comment]
here is another implementation that only sorts in development environment and does not require you to change any of your own code and is easy to remove once v3 is out:

```
import { combineReducers as combineReducersRedux } from 'redux';

// sorting of reducer keys can be removed once react-dev-tools v3 is released
const combineReducers = process.env.NODE_ENV !== 'development'
  ? combineReducersRedux
  : reducers => combineReducersRedux(Object.keys(reducers)
    .sort()
    .reduce((a, c) => {
      a[c] = reducers[c]; // eslint-disable-line
      return a;
    }, {}));
```
