### ISSUE TITLE
React-Native Transform Error - Preset "es2015-loose"

### ISSUE THREAD

**Issue by paulxtiseo** [gaearon/redux-devtools-log-monitor#34]
I have a new React native project. I am using `react-native@0.19.0`, `react-redux@4.4.0`, `redux@3.3.1`, `redux-devtools@3.1.1` and `redux-devtools-log-monitor@1.0.4`. Everything compiled fine when calling `react-native run-ios` until I added this `redux-devtools-log-monitor` library. Now, I get the following error in Packager:

```
[12:48:31 PM] <START> transform
transforming [====================================    ] 89% 685/769 Error while persisting cache: TransformError: /<path>/node_modules/redux-devtools-log-monitor/lib/index.js: Couldn't find preset "es2015-loose" relative to directory "/<path>/node_modules/redux-devtools-log-monitor"
```

Any suggestions?

PS: `<path>` in the error above is obviously the full path to the project that I removed...

**Comment by paulxtiseo** [comment]
Uninstalling `npm uninstall redux-devtools-log-monitor@1.0.4` leads to a new error:

```
Error while persisting cache: TransformError: /<path>/node_modules/react-pure-render/function.js: [BABEL] /<path>/node_modules/react-pure-render/function.js: Unknown option: /<path>/node_modules/react-pure-render/.babelrc.stage
```

**Comment by zalmoxisus** [comment]
How do you expect to use `redux-devtools-log-monitor` on React Native since it renders a HTML?

You should use [`remote-redux-devtools`](https://github.com/zalmoxisus/remote-redux-devtools).

**Comment by paulxtiseo** [comment]
Ok, that's embarrassing! :) Someone recommended it and I just started looking without RTFM. My bad.

I'll uninstall and look at your suggested library...

**Comment by zalmoxisus** [comment]
Anyway, I guess we should exclude `.babelrc` from the npm package or better use `files` attribute in `package.json`.

**Comment by gaearon** [comment]
>or better use files attribute in package.json.

Will merge a PR doing this (src + lib).

**Comment by zalmoxisus** [comment]
@gaearon, done in #35. BTW, I like the idea of including also the `src` folder in order to investigate the package. Will do this for my projects as well.
