### ISSUE TITLE
expand action payload by default

### ISSUE THREAD

**Issue by dmnd** [gaearon/redux-devtools-log-monitor#37]
When using [flux standard actions](https://github.com/acdlite/flux-standard-action) I have to click the `payload` property to see the contents of the action. I guess I could stop using FSA, but another option could be for LogMonitor to expand the payload by default.

**Comment by pke** [comment]
:+1: Or does the log monitor support transformations like redux-logger? Then the FSA actions could be flattened.

**Comment by gaearon** [comment]
You can track https://github.com/chibicode/react-json-tree/pull/31. When/if it’s merged, feel free to send a PR that uses it to implement something like what you describe here.

**Comment by gaearon** [comment]
This is now available so please feel free to send a PR that exposes that prop in some sensible way here.
