### ISSUE TITLE
LogMonitorEntry does not show 'state' and 'action' anymore but only 'root'

### ISSUE THREAD

**Issue by larrydahooster** [gaearon/redux-devtools-log-monitor#39]
With the upgrade from v1.0.2 to v1.0.3 the react-json-tree module was changed from ^v0.3.0 to ^v0.5.1. 
But v0.5.6 somehow causes a problem, as the [keyName](https://github.com/gaearon/redux-devtools-log-monitor/blob/master/src/LogMonitorEntry.js#L43) property somehow does no longer work and the state tree does no longer get rendered as expected. 

![bildschirmfoto 2016-03-01 um 17 11 48](https://cloud.githubusercontent.com/assets/4989851/13435084/c8a81ae8-dfd8-11e5-88eb-a026397e745d.png)

**Comment by gaearon** [comment]
I locked `react-json-tree` at `0.5.5` until this is resolved.
