### ISSUE TITLE
payload.error not displayed

### ISSUE THREAD

**Issue by pke** [gaearon/redux-devtools-log-monitor#40]
`redux-logger` does display the action correct as you can see on this screenshot.

![image](https://cloud.githubusercontent.com/assets/164625/13636342/c37abbaa-e601-11e5-8da4-36ef1f8aa681.png)

**Comment by kevana** [comment]
Seeing the same issue:

<img width="205" alt="screen shot 2016-03-14 at 12 35 40 pm" src="https://cloud.githubusercontent.com/assets/981551/13753569/76ddc9c0-e9e1-11e5-9550-4733624d4ecf.png">
<img width="234" alt="screen shot 2016-03-14 at 12 36 13 pm" src="https://cloud.githubusercontent.com/assets/981551/13753576/7929097e-e9e1-11e5-85fa-5e7def223bf2.png">

But I think this error is down in `react-json-tree`, not the log monitor.

**Comment by gaearon** [comment]
Please track this in https://github.com/chibicode/react-json-tree/issues/22. If this is fixed upstream, it will work here too.

**Comment by alexkuz** [comment]
Should be fixed in `v0.6.7`
