### ISSUE TITLE
Webpack with Babel 6 causes errors because of .babelrc files

### ISSUE THREAD

**Issue by josvos** [gaearon/redux-devtools-log-monitor#42]
Using webpack (with babel-loader) causes errors like "Using removed Babel 5 option".  Removing or renaming all (5) .babelrc files in the node_modules/redux-devtools-log-monitor tree solves this problem.

**Comment by zalmoxisus** [comment]
See the [solution](https://github.com/gaearon/redux-devtools/issues/259#issuecomment-194943953). Also, if for some reason, you need babel to process `node_modules`, better to create PRs to those dependencies as [we did here](https://github.com/gaearon/redux-devtools-log-monitor/pull/35).

**Comment by gaearon** [comment]
Recent versions of `redux-devtools-log-monitor` [do not include `.babelrc` in npm package](https://github.com/gaearon/redux-devtools-log-monitor/blob/00379fa62248b11f05a8160b5f6fd04047ee203b/package.json#L6-L9).

**Comment by gaearon** [comment]
Also you definitely shouldn’t be transpiling third-party modules with Babel. All kinds of stuff can break
