### ISSUE TITLE
Upgrade react-json-tree

### ISSUE THREAD

**Issue by SimenB** [gaearon/redux-devtools-log-monitor#43]
In particular I'm interested in chibicode/react-json-tree#38 (released as `0.6.3`)

**Comment by gaearon** [comment]
I tried updating it but so far I can’t get arrows to display with good margins:

<img width="147" alt="screen shot 2016-04-02 at 19 41 07" src="https://cloud.githubusercontent.com/assets/810438/14228380/e2adb4ca-f90a-11e5-8b13-f23056098f35.png">

Not sure why this is broken.

**Comment by gaearon** [comment]
Should be out now.

**Comment by SimenB** [comment]
Sweet, thanks!
