### ISSUE TITLE
Server Side Rendering - React Invalid Checksum

### ISSUE THREAD

**Issue by sunyang713** [gaearon/redux-devtools-log-monitor#44]
Hi, so the server renders `cursor:text;`, but the client renders `cursor:pointer;`. I think I've traced the responsible line to [this location](https://github.com/gaearon/redux-devtools-log-monitor/blob/master/src/LogMonitorButton.js#L81)

I went in and manually poked around to try and test different solutions, it looks like the if-enabled conditional is the section that causes the difference between the server and the client.

In addition, it seems that the server rendered markup will be missing any initial app actions, for example `@@Router/LOCATION_CHANGE` and all of its contents, whereas the client-side render will have this immediately, resulting in another invalid checksum. Do you happen to know why this is?

**Comment by gaearon** [comment]
I think it might be worth rendering DevTools on the client only, as indeed some action don’t make sense on the client, and they won’t always match.

**Comment by sunyang713** [comment]
hey, cool thanks for the suggestion. I think that's a good solution, render the Devtools in a different mount-node in development, so it's only rendered client-side and won't interfere with SSR.

```javascript
ReactDOM.render(<App />, 'root')
ReactDOM.render(<DevTools />, 'dev-tools')
```
