### ISSUE TITLE
React peer dependency version inconsistency

### ISSUE THREAD

**Issue by penmanglewood** [gaearon/redux-devtools-log-monitor#67]
This package's peer dependency with React is `"^0.14.9 || ^15.3.0"`, but the dependency `react-json-tree`'s [peer dependency with React](https://github.com/alexkuz/react-json-tree/blob/master/package.json#L64) is `"^15.0.0"`.

I have a React app that's still on 0.14.9, and I have a host of problems with this setup, including shrinkwrap will refuse to run because my React version doesn't meet `react-json-tree`'s requirements.

I guess the answer here would be to remove `^0.14.9` as an option, so it's clear which version of React is needed.

**Comment by zalmoxisus** [comment]
You're right. Changed in `redux-devtools-log-monitor@1.4.0`.
