### ISSUE TITLE
Can you please move "styles" into the props

### ISSUE THREAD

**Issue by globexdesigns** [gaearon/redux-devtools-log-monitor#8]
@gaearon You mentioned in another another issue that the reason you're using inline styles vs. CSS  classes is because you think it's easy enough to clone the LogMonitor to make theming changes. 

However, there are two big reasons why cloning the LogMonitor as a theming tool is a pain at the moment:

1) It forks the code. So no new updates to the main LogMonitor code base will be pulled in anymore.
2) It's actually quite a lot of steps to clone the LogMonitor. It requires copying the code (for all the nested components), installing all the required required dependencies, rebuilding the app, etc...

It's a big effort when all you want to do is make the font-size 1px smaller.

Would you consider moving the "styles" into a prop instead so at least the inline styles can be overwritten?

**Comment by gaearon** [comment]
Maybe we can use something like https://github.com/prometheusresearch/react-stylesheet to make them configurable?

**Comment by globexdesigns** [comment]
Sure that would work, or just use CSSmodules instead https://github.com/css-modules/css-modules

**Comment by gaearon** [comment]
The reason I don’t want to do this is this makes every internal style change a breaking change. Since we follow semver, we don’t want to break people all the time, or to increment majors on every version.
