### ISSUE TITLE
Add prop to "startCollapsed"

### ISSUE THREAD

**Issue by globexdesigns** [gaearon/redux-devtools-log-monitor#9]
I care most about "what actions are fired" and very rarely about "what is the current state of my stores". Because of this, it would like a way to specify in the devtools to always start in a fully collapsed view for the root JSONTree node. Like this:

![capture](https://cloud.githubusercontent.com/assets/226640/10960636/20b696b6-833a-11e5-8757-ac1799a6fe43.PNG)

This way I maximize the view on the names of the actions and not on the very large list of stores in our app.

Can you please add a prop to allow the LogMonitor to collapse the root nodes by default?

**Comment by henrybaxter** [comment]
+1 and I like that #16 has action and state separately (I prefer actions open and states collapsed)

**Comment by jasonslyvia** [comment]
+1 for this feature

**Comment by gaearon** [comment]
Since v1.0.2, it is possible by specifying `expandStateRoot={false}` as a prop.
